# Linear Algebra 1

In [2]:
import tensorflow as tf
import torch
import numpy as np

## Tensors

### Scalars (Rank 0 Tensors) in Base Python

In [3]:
x = 25
x

25

In [4]:
type(x) # if we'd like more specificity (e.g., int16, uint8), we need NumPy or another numeric library

int

In [5]:
y = 5

In [6]:
sum = x + y
sum

30

In [7]:
type(sum)

int

In [8]:
float_x = 25.0
sum2 = float_x + y
sum2

30.0

In [9]:
type(sum2)

float

### Scalars (Rank 0 Tensors) in Pytorch

In [10]:
x_pt = torch.tensor(25) # type: dtype=torch.float16
x_pt

tensor(25)

In [11]:
x_pt.shape

torch.Size([])

### Scalars (Rank 0 Tensors) in Tensorflow

In [14]:
x_tf = tf.Variable(25, dtype=tf.int16)
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [15]:
x_tf.shape

TensorShape([])

In [16]:
y_tf = tf.Variable(5, dtype=tf.int16)

In [17]:
x_tf + y_tf

<tf.Tensor: shape=(), dtype=int16, numpy=30>

In [18]:
sum_tf = tf.add(x_tf, y_tf)
sum_tf

<tf.Tensor: shape=(), dtype=int16, numpy=30>

In [19]:
sum_tf.numpy() #NumPy operations automatically convert tensors to NumPy arrays, and vice versa

30

In [20]:
type(sum_tf.numpy())

numpy.int16

In [21]:
tf_float = tf.Variable(25, dtype=tf.float16)
tf_float

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=25.0>

In [22]:
type(tf_float.numpy())

numpy.float16

### Vectors (Rank 1 Tensors) in Numpy

In [23]:
x = np.array([2,3,4])
x

array([2, 3, 4])

In [24]:
len(x)

3

In [25]:
x.shape

(3,)

In [26]:
type(x)

numpy.ndarray

In [27]:
x[1]

3

In [28]:
type(x[1])

numpy.int64

### Vector Transposition

In [29]:
x.T # no effect in 1-D array

array([2, 3, 4])

In [30]:
x.T.shape

(3,)

In [31]:
y = np.array([[2, 3, 4]]) # ...but it does when we use nested "matrix-style" brackets

In [32]:
y.shape

(1, 3)

In [33]:
y.T

array([[2],
       [3],
       [4]])

In [34]:
y.T.shape

(3, 1)

In [35]:
# Zero Vectors:
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

### Vectors (Rank 1 Tensors) in Pytorch

In [63]:
x_pt = torch.tensor([2,3,4])
x_pt

tensor([2, 3, 4])

In [79]:
x_pt[2]

tensor(4)

In [65]:
x_pt.shape

torch.Size([3])

In [66]:
x_pt.T.shape # no effect in 1-D array like before

torch.Size([3])

In [71]:
y_pt = torch.tensor([[2,3,4]]) # but works when we use "matrix-style" brackets

In [68]:
y_pt.shape

torch.Size([1, 3])

In [69]:
y_pt.T

tensor([[2],
        [3],
        [4]])

In [70]:
y_pt.T.shape

torch.Size([3, 1])

### Vectors (Rank 1 Tensors) in Tensorflow

In [74]:
x_tf = tf.Variable([2,3,4])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

In [75]:
x_tf.numpy()

array([2, 3, 4], dtype=int32)

In [77]:
x_tf[2].numpy()

4

In [80]:
x_tf.shape

TensorShape([3])

In [85]:
tf.transpose(x_tf).shape # no effect in 1-D array like before

TensorShape([3])

In [86]:
y_tf = tf.Variable([[2,3,4]]) # but works when we use "matrix-style" brackets

In [87]:
y_tf.shape

TensorShape([1, 3])

In [89]:
tf.transpose(y_tf)

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[2],
       [3],
       [4]], dtype=int32)>

In [90]:
tf.transpose(y_tf).shape

TensorShape([3, 1])

### *L*<sup>2</sup> Norm

In [91]:
x

array([2, 3, 4])

In [94]:
(2**2 + 3**2 + 4**2)**(1/2)

5.385164807134504

In [93]:
np.linalg.norm(x)

5.385164807134504

In [107]:
torch.linalg.norm(torch.tensor([2,3,4], dtype=torch.float16))

tensor(5.3867, dtype=torch.float16)

In [110]:
torch.linalg.vector_norm(torch.tensor([2,3,4], dtype=torch.float16))

tensor(5.3867, dtype=torch.float16)

In [106]:
tf.norm(tf.Variable([2,3,4], dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=5.387>

Vector with norm 1 is called **unit vector**

### *L*<sup>1</sup> Norm

In [111]:
x

array([2, 3, 4])

In [114]:
np.abs(x[0]) + np.abs(x[1]) + np.abs(x[2])

9

### Squared *L*<sup>2</sup> Norm

In [116]:
x

array([2, 3, 4])

In [117]:
2**2 + 3**2 + 4**2

29

In [120]:
np.dot(x, x)

29

### Max / *L*<sup>∞</sup> Norm 

In [123]:
np.max([np.abs(x[0]), np.abs(x[1]), np.abs(x[2])])

4

### Orthogonal Vectors

In [124]:
i = torch.tensor([1, 0])
i

tensor([1, 0])

In [126]:
j = torch.tensor([0, 1])
j

tensor([0, 1])

In [131]:
torch.dot(i, j)

tensor(0)

In [132]:
np.dot(i, j)

0

### Matrices (Rank 2 Tensors) in NumPy

In [133]:
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [134]:
X.shape

(3, 2)

In [135]:
X.size

6

In [145]:
X[:,0] # left column

array([25,  5,  3])

In [146]:
X[:,1] # right column

array([ 2, 26,  7])

In [155]:
X[0:2]

array([[25,  2],
       [ 5, 26]])

### Matrices (Rank 2 Tensors) in PyTorch

In [164]:
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [165]:
X_pt.shape

torch.Size([3, 2])

In [166]:
X_pt[1]

tensor([ 5, 26])

In [167]:
X_pt[:,0]

tensor([25,  5,  3])

In [168]:
X_pt[:,1]

tensor([ 2, 26,  7])

### Matrices (Rank 2 Tensors) in Tensorflow

In [169]:
X_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [172]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [173]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [174]:
X_tf[1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26], dtype=int32)>

In [175]:
X_tf[:,0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([25,  5,  3], dtype=int32)>

In [177]:
X_tf[:,1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 2, 26,  7], dtype=int32)>

### Higher-Rank Tensors
As an example, rank 4 tensors are common for images, where each dimension corresponds to:

1. Number of images in training batch, e.g., 32
2. Image height in pixels, e.g., 28 for MNIST digits
3. Image width in pixels, e.g., 28
4. Number of color channels, e.g., 3 for full-color images (RGB)

In [180]:
images_pt = torch.zeros([32, 28, 28, 3])
# images_pt

In [181]:
images_tf = tf.zeros([32, 28, 28, 3])
# images_tf

In [184]:
images = np.zeros([32, 28, 28, 3])
# images

In [193]:
Rank3 = tf.Variable([[[1, 2], [2, 3]]])
tf.rank(Rank3)

<tf.Tensor: shape=(), dtype=int32, numpy=3>